#!/usr/bin/env bash

# Taps
tap 'homebrew/core'
tap 'homebrew/bundle'
tap 'homebrew/cask'
tap 'homebrew/cask-versions'
tap 'buo/cask-upgrade'

# Binaries
brew 'coreutils'
brew 'curl'
brew 'git'
brew 'git-flow'
brew 'gnupg'
brew 'grep'
brew 'httpie'
brew 'mackup'
brew 'mas'
brew 'readline'
brew 'openssl'
brew 'php'
brew 'trash'
brew 'tree'
brew 'wget'
brew 'zsh'

# Apps
cask '1password'
cask 'aerial'
cask 'alfred'
cask 'amethyst'
cask 'bartender'
cask 'cleanmymac'
cask 'choosy'
cask 'cryptomator'
cask 'cyberduck'
cask 'dash'
cask 'evernote'
cask 'firefox'
cask 'firefox-developer-edition'
cask 'flux'
# cask 'gpg-suite'
cask 'imageoptim'
cask 'insomnia'
cask 'iconjar'
cask 'iterm2'
cask 'jetbrains-toolbox'
cask 'keepingyouawake' 
cask 'liteicon'
cask 'neofinder'
cask 'nightowl'
cask 'protonmail-bridge'
cask 'protonvpn'
cask 'recordit'
cask 'sequel-pro'
cask 'signal'
cask 'sketch'
cask 'soundmate'
cask 'spotify'
cask 'sync'
cask 'transmission'
cask 'vagrant'
cask 'virtualbox'
cask 'virtualbox-extension-pack'
cask 'visual-studio-code'
cask 'vlc'
cask 'wavebox'

# Quicklook
cask 'qlcolorcode'
cask 'qlmarkdown'
cask 'quicklook-json'
cask 'quicklook-csv'
cask 'qlstephen'

# Fonts

# Mac App Store
mas 'LINE', id: 539883307
mas 'iA Writer', id: 775737590
mas 'LittleIpsum', id: 405772121
mas 'Bear', id: 1091189122
mas 'Type Fu', id: 509818877
mas 'UlyssesMac', id: 1225570693
mas 'SoundMate', id: 675025930
mas 'Pocket', id: 568494494
mas 'Numbers', id: 409203825
mas 'Keynote', id: 409183694
mas 'Clear', id: 504544917
mas 'Magnet', id: 441258766
mas 'The Clock', id: 488764545
mas 'Pages', id: 409201541