alias nvm='n (cat .nvmrc)'
alias nrw='npm run watch'
alias nrp='npm run prod'
alias nrd='npm run dev'
alias nrb='npm run build'
alias nrg='npm run generate'
alias nrh='npm run hot'
alias nrl='npm run lint'
alias nrs='npm run serve'
alias nlg='npm -g list --depth=0'
alias ncs='npm-check --skip-unused'
