#!/usr/bin/env bash

# Taps
tap "buo/cask-upgrade"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
# tap "nektos/tap"

# Binaries
# brew 'nektos/tap/act'
brew 'coreutils'
brew 'curl'
brew 'ffmpeg'
brew 'git'
brew 'git-flow-avh'
brew 'git-lfs'
brew 'gnupg'
brew 'grep'
brew 'httpie'
brew 'lsd'
brew 'mackup'
brew 'mas'
brew 'readline'
brew 'openssl'
brew 'php'
brew 'tig'
brew 'trash'
brew 'tree'
brew 'starship'
brew 'wget'
brew 'youtube-dl'
brew 'zsh'

# Apps
cask '1password'
cask 'aerial'
cask 'alfred'
# cask 'amethyst'
cask 'bartender'
cask 'cleanmymac'
cask 'choosy'
cask 'cryptomator'
cask 'dash'
cask 'evernote'
cask 'firefox'
cask 'firefox-developer-edition'
cask 'flux'
cask 'gitfox'
# cask 'gpg-suite'
# cask 'gpg-suite-nightly'
cask 'insomnia'
cask 'iconjar'
cask 'iterm2'
cask 'jaxx-liberty'
cask 'jetbrains-toolbox'
cask 'keepingyouawake' 
cask 'liteicon'
cask 'logitech-options'
cask 'neofinder'
cask 'nightowl'
cask 'nordvpn'
cask 'notion'
cask 'numi'
cask 'optimage'
cask 'protonmail-bridge'
cask 'raindropio'
cask 'recordit'
cask 'sequel-pro'
cask 'signal'
cask 'sketch'
cask 'spotify'
cask 'sync'
cask 'transmission'
cask 'transmit'
cask 'vagrant'
cask 'virtualbox'
cask 'virtualbox-extension-pack'
cask 'visual-studio-code'
cask 'vlc'
cask 'wavebox'
cask 'zotero'

# Quicklook
cask 'qlcolorcode'
cask 'qlmarkdown'
cask 'quicklook-json'
cask 'quicklook-csv'
cask 'qlstephen'

# Drivers
cask 'canon-imagerunner-printer-driver-ufrii' # UZH Printer

# Fonts
cask "font-fira-code"
cask "font-fira-mono"
cask "font-fira-sans"
cask "font-firacode-nerd-font"
cask "font-firacode-nerd-font-mono"
cask "font-hack"
cask "font-hack-nerd-font"
cask "font-ia-writer-duo"
cask "font-ia-writer-duospace"
cask "font-ia-writer-mono"
cask "font-ia-writer-quattro"
cask "font-lato"
cask "font-playfair-display"
cask "font-public-sans"
cask "font-roboto"
cask "font-saira"

# Mac App Store
mas "Bear", id: 1091189122
mas "Clear", id: 504544917
mas "iA Writer", id: 775737590
mas "Keynote", id: 409183694
mas "LINE", id: 539883307
mas "LittleIpsum", id: 405772121
mas "Magnet", id: 441258766
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Pocket", id: 568494494
mas "SoundMate", id: 675025930
mas "Tadam", id: 531349534
mas "Take a Break", id: 1457158844
mas "The Clock", id: 488764545
mas "Type Fu", id: 509818877
mas "Ulysses", id: 1225570693
mas "Xcode", id: 497799835