#!/usr/bin/env bash

# Taps
tap 'homebrew/bundle'
tap 'homebrew/cask'
tap 'homebrew/cask-fonts'
tap 'homebrew/cask-drivers'
tap 'homebrew/cask-versions'
tap 'homebrew/services'

# Binaries
brew 'bluetoothconnector'
brew 'coreutils'
brew 'curl'
brew 'ffmpeg'
brew 'fish'
brew 'git'
brew 'git-lfs'
brew 'gh'
brew 'gitui'
brew 'gnupg'
brew 'grep'
brew 'htop'
brew 'httpie'
brew 'lsd'
brew 'n'
brew 'mackup'
brew 'mas'
brew 'openssl'
#brew 'php'
brew 'pinentry'
brew 'supervisor'
brew 'svn'
brew 'tig'
brew 'trash'
brew 'tree'
brew 'wget'
brew 'youtube-dl'

# Apps
cask '1password'
#cask 'aerial'
#cask 'adobe-creative-cloud'
#cask 'aldente-pro'
cask 'atext'
cask 'backblaze'
cask 'bartender'
cask 'bunch'
#cask 'carbon-copy-cloner'
cask 'cleanmymac'
#cask 'cryptomator'
cask 'dash'
cask 'dbngin'
cask 'dictcc-en-de-dictionary-plugin'
#cask 'discord'
#cask 'deckset'
cask 'figma'
cask 'firefox'
cask 'firefox-developer-edition'
#cask 'gitfox'
cask 'google-chrome'
cask 'gpg-suite'
cask 'hazel'
#cask 'iconjar'
cask 'insomnia'
cask 'iterm2'
cask 'jetbrains-toolbox'
cask 'logi-options-plus'
#cask 'loom'
#cask 'microsoft-teams'
#cask 'mmhmm'
cask 'monitorcontrol'
cask 'mountain-duck'
cask 'neofinder'
cask 'notion'
cask 'numi'
cask 'optimage'
#cask 'phpmon'
cask 'pixelsnap'
cask 'ray'
cask 'raycast'
#cask 'rightfont'
cask 'recordit'
cask 'safari-technology-preview'
cask 'selfcontrol'
cask 'shifty'
cask 'signal'
cask 'slack'
cask 'smoothscroll'
#cask 'soundcleod'
cask 'spotify'
cask 'sync'
cask 'tableplus'
cask 'telegram'
cask 'tinkerwell'
#cask 'the-archive'
cask 'tower'
cask 'transmission'
cask 'transmit'
#cask 'tripmode'
#cask 'visual-studio-code'
cask 'vlc'
cask 'wavebox'
cask 'zoom'
cask 'zotero'

# Quicklook: Check which ones are still working
#cask 'qlcolorcode'
#cask 'qlmarkdown'
#cask 'quicklook-json'
#cask 'quicklook-csv'
#cask 'qlstephen'
#cask 'qlimagesize'
#cask 'quicklookase'
#cask 'qlvideo'

# Fonts
cask 'font-fira-code'
cask 'font-fira-mono'
cask 'font-fira-sans'
cask 'font-hack'
cask 'font-jetbrains-mono'
cask 'font-public-sans'

cask 'font-playfair-display'
cask 'font-lato'
cask 'font-dm-sans'

#cask 'font-ia-writer-duo'
#cask 'font-ia-writer-duospace'
#cask 'font-ia-writer-mono'
#cask 'font-ia-writer-quattro'

# Mac App Store
mas '1Password for Safari', id: 1569813296
mas 'Amphetamine', id: 937984704
mas 'Bike', id: 1588292384
mas 'Color Picker', id: 1545870783
mas 'Cookie', id: 1473091386
mas 'Dark Mode Wallpaper', id: 1488154568
mas 'EasyLetter', id: 1495179755
mas 'Endel', id: 1484348796
#mas 'Final Cut Pro', id: 424389933
#mas 'Gestimer', id: 990588172
#mas 'Gifski', id: 1351639930
mas 'Harvest', id: 506189836
mas 'Hue Menu Bar', id: 1500678169
mas 'Hush', id: 1544743900
mas 'iA Writer', id: 775737590
mas 'Infuse', id: 1136220934
#mas 'Jiffy', id: 1502527999
mas 'Kagi Inc.', id: 1622835804
mas 'Keynote', id: 409183694
mas 'LINE', id: 539883307
mas 'Little Snitch Mini', id: 1629008763
mas 'Magnet', id: 441258766
mas 'Mela', id: 1568924476
mas 'Muse', id: 1501563902
# mas 'Name Mangler', id: 603637384
mas 'NextDNS', id: 1464122853
mas 'Numbers', id: 409203825
mas 'Noteship', id: 1571711347
mas 'Pages', id: 409201541
mas 'Pandan', id: 1569600264
mas 'PDFify', id: 1435055351
mas 'Pixelmator Pro', id: 1289583905
mas 'Pocket', id: 568494494
mas 'Poolsuite FM', id: 1514817810
mas 'Pomy', id: 1422640635
mas 'Pure Paste', id: 1611378436
mas 'Reeder', id: 1529448980
mas 'Save to Pocket', id: 1477385213
mas 'SiteSucker', id: 442168834
mas 'Speediness', id: 1596706466
mas 'Tailscale', id: 1475387142
mas 'Tampermonkey', id: 1482490089
mas 'TestFlight', id: 899247664
mas 'The Clock', id: 488764545
mas 'Things', id: 904280696
mas 'ToothFairy', id: 1191449274
mas 'Ulysses', id: 1225570693
mas 'Velja', id: 1607635845
mas 'WiFi Explorer', id: 494803304
mas 'Wipr', id: 1320666476
mas 'Xcode', id: 497799835
